### ISSUE TITLE
Usage if pretty permalink are not enabled?

### ISSUE THREAD

**Issue by flegfleg** [WPBP/FakePage#2]
Hi, i am trying to get this class to work when pretty permalinks are not enabled (e.g. `?p=123 ` ). 
Is it possible? Any hint? Thanks.

**Comment by Mte90** [comment]
Good point actually I don't think that work because require the slug at any cost, the slug is used as reference.

**Comment by Mte90** [comment]
I checked the code, this class cannot work without pretty permalink because use a fake id.
It is not possible to use it without or the url is very horrible.
